# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "source{d} tech talks"
email: "talks@sourced.tech"
description: "source{d} tech talks is a one day conference about infrastructure"
baseurl: ""
url: "http://talks.sourced.tech"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-69608223-4"
googleAnalyticsSiteUrl: "talks.sourced.tech"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "source{d}"
organizerAlternateName: "source{d} tech talks"
organizerDescription: "source{d} tech talks is a one-day conference about Infrastructure"
organizerEmail: "talks@sourced.tech"
organizerLogo: "http://sourced.tech/img/logos/logo-blue.svg"
organizerLink: "http://sourced.tech/"

# Head
metaKeywords: "event, talks, tech, srcd, devops, infrastructure, sourced, developers, madrid"
twitterAccount: "@srcd_"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png?v=2"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png?v=2"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png?v=2"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {link: "https://blog.sourced.tech", text: "Blog"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/sourced-tech-talks-infrastructure-tickets-32181636140", text: "Get your ticket"}

# Hero Block
heroImage: "venue/turing.jpg"
heroTitle: "source{d} tech talks <typeout> 2017"
eventDate: "Infrastructure Series - 25th of March"
typeoutTextValues: '"Infrastructure", "Madrid", "First Series"'
typeoutFallback: "Infrastructure"
heroButtons:
 - {link: "https://www.eventbrite.com/e/sourced-tech-talks-infrastructure-tickets-32181636140", text: "Get your ticket"}

# About Block
aboutTitle: "About our tech talks"
aboutIntro: "We will be hosting great speakers in an informal setting <strong>every ~3 months</strong>. Each series of talks will cover a different topic <strong>targeted to an experienced technical audience</strong>. Speakers will be invited both <strong>from Spain and abroad</strong>."

aboutBlock:
 - {title: "Main Talks", image: "main-talks-icon.jpg", text: "We will hold five main talks throughout the day. These will last for 45min with time for Q&A." }
 - {title: "Lightning Talks", image: "lightning-talks-icon.jpg", text: "There will be two shorter talks held to address more specific topics." }
 - {title: "Food & Beers", image: "food-beers.jpg", text: "Besides breakfast, lunch and snacks, we will be launching our very own source{d} beer that day!" }


# Statistic Block
statisticBlockImage: "venue/lovelace.jpg"
statisticBlock:
 - {count: "75", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of pure Infrastructure talks"}
 - {count: "7", info: "speakers", detail: "from Spain and beyond"}


# Rockstar Speakers Block
rockstarSpeakersImage: "venue/turing.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Some speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "source{d} offices"
eventStreetAddress: "Claudio Coello 16, 2 Izq."
eventAddressLocality: "Madrid"
eventPostalCode: "28001"
eventAddressCountry: "Spain"
eventStartTime: "2017-03-25T09:30"
eventDoorTime: "09:30"
eventEndTime: "2017-03-25T17:30"
eventLocationMap: "https://www.google.es/maps/place/Calle+de+Claudio+Coello,+16,+28001+Madrid/"
eventPlaceCoordinates: "40.422259,-3.6866953999999623"
mapCenterCoordinates: "40.4222631,-3.6888894"
mapMobileCenterCoordinates: "40.4222631,-3.6888894"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweet us at"
twitterHashTag: "sourcedtalks"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
#organizersTitle: "Organizers"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "venue/ritchie.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://eepurl.com/cCoHPf"
subscribeInfo: "Registration will be open until the day before the event but attendees are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://github.com/src-d/", icon: "github"}
 - {link: "https://twitter.com/srcd_", icon: "twitter"}
 - {link: "https://www.linkedin.com/company/10284920/", icon: "linkedin"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://sourced.tech/", text: "sourced{d}"}
   - {link: "https://blog.sourced.tech/", text: "blog"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:talks@sourced.tech", text: "talks@sourced.tech"}
